# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish to NPM

on:  
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - run: yarn run build
      - run: yarn run test
        env:
          FORGE_BUCKET: ${{secrets.FORGE_BUCKET}}
          FORGE_CLIENT_ID: ${{secrets.FORGE_CLIENT_ID}}
          FORGE_CLIENT_SECRET: ${{secrets.FORGE_CLIENT_SECRET}}
          FORGE_MODEL_URN: ${{secrets.FORGE_MODEL_URN}}
      - run: yarn run docs

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn run build
      - run: yarn run docs
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
